"""
validation and classes for a Factory Output Plan

includes
- power constraints
- cross-region transfer
- cross-region transfer (manual)
"""

from math import ceil
from typing import Final, NamedTuple

from akef.recipe import ItemBatch, ItemFlow, Recipe
from akef.recipe_list import facility_list, items


class RegionPlanConstraints(NamedTuple):
    region_name: str
    raw_income: ItemFlow
    """income of the raw resources for the region"""
    value: ItemBatch
    """value weights of each item"""

    base_load: int
    """base load to power drills, turrets, ziplines, etc."""
    base_power: int = 200
    """base power generated by the PAC"""


class PlanConstraints(NamedTuple):
    regions: list[RegionPlanConstraints]
    max_cross_transfer_rate: float
    """how much are you willing to manually transfer XD"""


class RegionPlan(NamedTuple):
    config: RegionPlanConstraints

    sell_plan: ItemFlow = {}
    power_plan: ItemBatch = {}
    profit: float = 0.0
    facility_plan: ItemBatch = {}
    recipe_plan: list[tuple[Recipe, float]] = []
    cross_transfer: dict[str, ItemFlow] = {}


class Plan:
    def __init__(self, regions: list[RegionPlan]) -> None:
        self.regions: Final = regions
        self.valid: Final = self._validate()

    def _validate(self) -> bool:
        region_net: dict[str, ItemFlow] = {}
        req_facilities: dict[str, ItemBatch] = {}
        for r in self.regions:
            region_net[r.config.region_name] = {k: 0.0 for k in items}
            req_facilities[r.config.region_name] = {k.name: 0 for k in facility_list}

        for r in self.regions:
            local_net = region_net[r.config.region_name]
            local_facility = req_facilities[r.config.region_name]
            for k, v in r.config.raw_income.items():
                local_net[k] += v
            for k, v in r.sell_plan.items():
                local_net[k] -= v
            for dest, item_flow in r.cross_transfer.items():
                for k, v in item_flow.items():
                    local_net[k] -= v
                    region_net[dest][k] += v
            for recipe, rate in r.recipe_plan:
                for k, v in recipe.input_flow.items():
                    local_net[k] -= v * rate
                for k, v in recipe.output_flow.items():
                    local_net[k] += v * rate
                local_facility[recipe.facility.name] += ceil(rate)

        # checks
        for region_name, local_net in region_net.items():
            for item_name, flow_rate in local_net.items():
                if flow_rate < 0:
                    print("Negative flow rate", region_name, item_name, flow_rate)
                    return False
        for region in self.regions:
            local_req_facilities = req_facilities[region.config.region_name]
            for facility, req_count in local_req_facilities.items():
                if region.facility_plan.get(facility, 0) < req_count:
                    return False

        return True
